# ClusterSecretStore for GCP Secret Manager
# This provides cluster-wide access to GCP Secret Manager for all ExternalSecrets
#
# Prerequisites:
# 1. ESO must be installed (helm install external-secrets external-secrets/external-secrets)
# 2. GCP Workload Identity must be configured
# 3. K8s ServiceAccount must be annotated with GCP SA
#
# Usage:
# ExternalSecrets reference this store with:
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: gcp-secret-manager
#
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
  labels:
    k3sapp.io/component: secrets
spec:
  provider:
    gcpsm:
      projectID: ${GCP_PROJECT_ID}
      auth:
        workloadIdentity:
          clusterLocation: ${GCP_REGION}
          clusterName: ${GCP_CLUSTER_NAME}
          clusterProjectID: ${GCP_PROJECT_ID}
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
