# ServiceAccount for External Secrets Operator
# Annotated with GCP Workload Identity binding
#
# This ServiceAccount is used by ESO to authenticate with GCP Secret Manager
# The GCP service account must have roles/secretmanager.secretAccessor
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets
  labels:
    k3sapp.io/component: secrets
  annotations:
    # GCP Workload Identity annotation
    # Replace ${GCP_PROJECT_ID} with your actual project ID
    iam.gke.io/gcp-service-account: external-secrets-sa@${GCP_PROJECT_ID}.iam.gserviceaccount.com
