# Valkey Helm Application for Local Environment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey
  namespace: argocd
  labels:
    app.kubernetes.io/component: database
    environment: local
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: valkey
    targetRevision: "*"  # Latest version
    helm:
      releaseName: valkey
      valueFiles: []
      values: |
        # Simplified values for local environment
        global:
          security:
            allowInsecureImages: true

        architecture: replication

        auth:
          enabled: true
          sentinel: true
          password: ""

        sentinel:
          enabled: true
          masterSet: myprimary
          quorum: 2

        primary:
          replicaCount: 1
          persistence:
            enabled: true
            size: 2Gi
            storageClass: "local-path"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi

        replica:
          replicaCount: 1
          persistence:
            enabled: true
            size: 2Gi
            storageClass: "local-path"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi

        networkPolicy:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
