apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k3s-platform
  namespace: argocd
spec:
  description: K3s Platform Applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
