#!/bin/bash
set -euo pipefail

#═══════════════════════════════════════════════════════════════════════════════
# Create New Serverless App
#
# Scaffolds a new serverless function app with the k3sfn SDK.
# Dockerfile is auto-generated by the CLI during deployment.
#
# Usage:
#   ./scripts/new-serverless-app.sh <app-name>
#
# Example:
#   ./scripts/new-serverless-app.sh my-api
#═══════════════════════════════════════════════════════════════════════════════

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

APP_NAME="${1:-}"

if [[ -z "$APP_NAME" ]]; then
    echo "Usage: $0 <app-name>"
    echo ""
    echo "Creates a new serverless function app with example functions."
    exit 1
fi

APP_DIR="${PROJECT_ROOT}/apps/${APP_NAME}"

if [[ -d "$APP_DIR" ]]; then
    echo "Error: App already exists: $APP_DIR"
    exit 1
fi

log_info "Creating serverless app: $APP_NAME"

# Create directory structure
mkdir -p "${APP_DIR}/functions"

# Create __init__.py
cat > "${APP_DIR}/functions/__init__.py" << EOF
"""
Serverless Functions for ${APP_NAME}

Define your functions here using the @serverless decorator.
"""

from .api import *
EOF

# Create example API function
cat > "${APP_DIR}/functions/api.py" << EOF
"""
HTTP API Functions
"""

from datetime import datetime
from typing import Any, Dict

from k3sfn import serverless, http_trigger, Request


@serverless(
    memory="256Mi",
    cpu="100m",
    min_instances=0,  # Scale to zero when idle
    max_instances=10,
    timeout=30,
)
@http_trigger(
    path="/api/hello",
    methods=["GET"],
)
async def hello(request: Request) -> Dict[str, Any]:
    """
    Example hello world function.

    Access at: /api/hello?name=World
    """
    name = request.query_params.get("name", "World")
    return {
        "message": f"Hello, {name}!",
        "timestamp": datetime.utcnow().isoformat(),
        "app": "${APP_NAME}",
    }


@serverless(
    memory="256Mi",
    cpu="100m",
    min_instances=0,
    max_instances=10,
    timeout=30,
)
@http_trigger(
    path="/api/echo",
    methods=["POST"],
)
async def echo(request: Request) -> Dict[str, Any]:
    """
    Echo back the request body.
    """
    return {
        "received": request.body,
        "timestamp": datetime.utcnow().isoformat(),
    }
EOF

# Create dev Dockerfile for Tilt hot-reload
cat > "${APP_DIR}/Dockerfile.dev" << EOF
# Development Dockerfile for serverless functions
# Supports hot-reload via Tilt live_update

FROM python:3.12-slim

WORKDIR /app

# Install pip dependencies
RUN pip install --no-cache-dir hatchling

# Install the SDK in development mode
COPY libs/k3sfn /app/libs/k3sfn
RUN pip install --no-cache-dir -e /app/libs/k3sfn

# Install runtime dependencies
RUN pip install --no-cache-dir fastapi uvicorn pydantic valkey pyyaml

# Copy function code
COPY apps/${APP_NAME}/functions /app/functions

# Runtime configuration
ENV PORT=8080
EXPOSE 8080

# Run the function server
CMD ["python", "-m", "k3sfn.runtime", "functions"]
EOF

# Generate initial manifests
log_info "Generating initial Kubernetes manifests..."
cd "${PROJECT_ROOT}"
if command -v uv &>/dev/null; then
    uv run python3 -m k3sfn.cli generate "${APP_DIR}" \
        --name "${APP_NAME}" \
        --output "${APP_DIR}/generated" \
        --namespace apps \
        --registry registry.localhost:5111 2>/dev/null || true
fi

log_success "Serverless app created: $APP_DIR"
echo ""
echo "Project structure:"
echo "  ${APP_DIR}/"
echo "  ├── functions/"
echo "  │   ├── __init__.py"
echo "  │   └── api.py"
echo "  ├── Dockerfile.dev    (for Tilt hot-reload)"
echo "  └── generated/        (K8s manifests, auto-generated)"
echo ""
echo "Next steps:"
echo "  1. Edit functions in ${APP_DIR}/functions/"
echo ""
echo "  2. Add to apps.yaml:"
echo "     serverless:"
echo "       - name: ${APP_NAME}"
echo "         path: apps/${APP_NAME}"
echo "         namespace: apps"
echo "         enabled: true"
echo ""
echo "  3. For local development:"
echo "     tilt up"
echo ""
echo "  4. Or deploy to cluster:"
echo "     ./scripts/deploy-apps.sh"
echo ""
