# Valkey Helm Application for GCP Environment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey
  namespace: argocd
  labels:
    app.kubernetes.io/component: database
    environment: gcp
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/GeeekyBoy/k3s-platform.git
    targetRevision: HEAD
    path: apps/valkey
    helm:
      releaseName: valkey
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
